/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Surface(props) {
  const { nodes, materials } = useGLTF('/surface.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Apollo_16.geometry} material={materials['Material.001']} position={[0, -7, 0]} />
    </group>
  );
}

useGLTF.preload('/surface.glb');
